### PR TITLE
check for Windows version 10

### PR DESCRIPTION
**Pull request by CudaText-addons**
I am on Win 7 now. pls check on Win10

### CODE REVIEW

**Comment by veksha** [comment]
Don't you think msg_box is too "intrusive"?
I can set text of memo and user will see it. Agree?

**Comment by veksha** [comment]
please check: e22625f

**Comment by Alexey-T** [comment]
agree.

**Comment by Alexey-T** [comment]
@veksha Now not agree! this still has crash on importing xxxx_pty. I made the fix - making new "win_ok.py" - but code looks awful. let's return to msgbox.

**Comment by veksha** [comment]
Oh. I see. returned to msg_box.
check this: be2a16a  ok?

**Comment by Alexey-T** [comment]
OK now

**Pull request merged**
